name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Configura el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # 3. Instalar las dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Configurar navegador y driver (Google Chrome y ChromeDriver)
      - name: Set up ChromeDriver
        uses: electronuserland/action-chromedriver@v1
        with:
          version: latest

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 5. Ejecutar las pruebas
      - name: Run tests
        run: |
          python run_tests.py
