name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Configura el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # 3. Instalar dependencias de Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Instalar Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 5. Instalar la versión correcta de ChromeDriver
      - name: Install ChromeDriver
      - uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      # 6. Ejecutar pruebas
      - name: Run tests
        run: |
          python run_tests.py

